[phases.setup]
nixPkgs = ['php', 'composer', 'nodejs', 'npm']

[phases.install]
cmds = ['chmod +x railway-build.sh', './railway-build.sh']

[start]
cmd = 'php artisan serve --host 0.0.0.0 --port $PORT'
